version: '3.9'

services:

    web:
        build: .
        volumes:
            - .:/usr/src/app
        ports:
            - "8000:8000"
        depends_on:
            - db

    db:
        image: postgres:15
        environment:
            POSTGRES_USER: "admin"
            POSTGRES_PASSWORD: "1234"
        volumes:
            - postgres_data:/var/lib/postgresql/data/
    
volumes:
    postgres_data: