# Generated by Django 4.2.4 on 2023-08-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("palinodes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="directory",
            name="description",
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
