# Generated by Django 4.2.4 on 2023-08-11 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("palinodes", "0002_directory_file_profile_repository_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="File",
            new_name="FileModel",
        ),
    ]
