# Generated by Django 4.2.4 on 2023-08-21 19:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("palinodes", "0002_alter_directory_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="directory",
            name="collaborators",
            field=models.ManyToManyField(
                blank=True, related_name="collaborating", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
