# Generated by Django 4.2.4 on 2023-08-18 10:18

from django.db import migrations, models
import palinodes.models


class Migration(migrations.Migration):

    dependencies = [
        ("palinodes", "0003_rename_file_filemodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="description",
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True, upload_to=palinodes.models.get_avatar_path
            ),
        ),
    ]
