# Generated by Django 4.2.4 on 2023-08-30 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("palinodes", "0003_alter_directory_collaborators"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="file",
        ),
        migrations.AddField(
            model_name="comment",
            name="repository",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coments",
                to="palinodes.directory",
            ),
            preserve_default=False,
        ),
    ]
