# Generated by Django 4.2.4 on 2023-08-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("palinodes", "0004_remove_comment_file_comment_repository"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="timestamp",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
