# Generated by Django 4.2.4 on 2023-08-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("palinodes", "0004_repository_description_alter_profile_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="description",
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
