# Generated by Django 4.2.4 on 2023-08-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("palinodes", "0005_profile_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="description",
            field=models.TextField(blank=True, default="", max_length=300),
        ),
    ]
