# Generated by Django 4.2.4 on 2023-08-30 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("palinodes", "0005_comment_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="repository",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="palinodes.directory",
            ),
        ),
    ]
