# Generated by Django 4.2.4 on 2023-08-31 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("palinodes", "0006_alter_comment_repository"),
    ]

    operations = [
        migrations.AddField(
            model_name="filemodel",
            name="uploaded",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
