# Generated by Django 4.2.4 on 2023-08-31 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("palinodes", "0007_filemodel_uploaded"),
    ]

    operations = [
        migrations.AlterField(
            model_name="directory",
            name="created",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
