# Generated by Django 4.2.4 on 2023-09-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("palinodes", "0008_alter_directory_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="directory",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="filemodel",
            name="uploaded",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
