# Generated by Django 4.2.4 on 2023-09-07 15:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("palinodes", "0013_alter_notification_recipients"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="recipients",
            field=models.ManyToManyField(
                blank=True, related_name="notifications", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
